name: CI/CD Workflow

on: 
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    # Commits with 'no-ci' in the message prevent the workflow from running
    # This is useful when commiting non code files, like the README for example
    if: ${{ !contains(github.event.head_commit.message, 'no-ci') }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessary for commits message check

     # Set up Julia
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10.2' # Specify the Julia version here; use '1.x' for the latest stable version

    # Prepare for testing
    - name: Install Dependencies and precompile
      run: |
        julia --project -e " /
          using Pkg; /
          Pkg.instantiate(); /
          Pkg.precompile(); "

    # Run your application's tests
    - name: Run tests
      run: |
        julia --project -e "include(\"test/runtests.jl\")"

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and tag your Docker application
    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/aircentre/julia-web-app-example:${{ github.sha }}

    # Push the Docker image to GitHub Container Registry
    - name: Push the Docker image to GHCR
      run: |
        docker push ghcr.io/aircentre/julia-web-app-example:${{ github.sha }}
